-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 97b88d9610bcc03982ddac33caba98bb2b751f5f
    stages:
    - commit
    #- push
    hooks:
    -   id: trailing-whitespace
        files: ''
        args:
        - --no-markdown-linebreak-ext
    #-   id: flake8
    #    args:
    #    - --max-line-length=131
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    #-   id: name-tests-test
    -   id: pretty-format-json
    -   id: requirements-txt-fixer
-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: 9cc8e5d5293f28d16d871b541c6465e916438241
    stages:
    - commit
    #- push
    hooks:
    -   id: yapf
-   repo: https://github.com/marick/pre-commit-hooks.git
    sha: 74e8eff3774a23c09b15b729cadc0ef39af0d356
    stages:
    - commit
    - push
    hooks:
    -   id: only-branch-pushes
        args:
        - prevent
        - ^(develop|master)$
