### Import Tag Step no FP ###6

#IMPORT
import: 
    write: yes
    autotag: yes
    resume: yes #no or ask
    incremental: no
    incremental_skip_later: no #skip dird
    from_scratch: no #existing meta?
    quiet_fallback: skip #asis
    none_rec_action: skip #asis, ask
    timid: no
    default_action: apply # skip, asis, none
    group_albums: yes
    duplicate_action: skip # keep, merge, remove, ask
    
    # files
    move: no
    copy: no
    delete: no
    link: no
    hardlink: no

    # general
    languages: ['en']
    detail: yes # shows match detail
    #set_fields:
        #genre: 'xxx'
        #comments: ''
    
    # feedback
    log: beets.log # where log kept
    bell: yes

# Auto Tagger --------------------------
match:
    strong_rec_thresh: 0.1  # match 90%
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: low #none, low, medi, strong
        unmatched_tracks: low
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.1 # 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    #required: year label catalognum country
    preferred:
        countries: ['US', 'GB', 'ZA', 'JP', 'XW', 'XE']       
        #media: ['CD', 'Digital Media|File', 'vinyl']
        original_year: yes
    ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD', 'VCD', 'SVCD', 'UMD', 'VHS']
    ignore_video_tracks: yes
    track_length_grace: 10
    track_length_max: 30


# Plugins --------------------------
plugins: [
    chroma,
    discogs,
    beatport,
    fromfilename
]

chroma:
    auto: yes

discogs:
    auto: yes
    #apikey: XuTzrVmWaGUEGTLdXPex
    #apisecret: TwMHrSDrNZvVcvSurnzaDFZVfLFtojXv
    #tokenfile: discogs_token.json
    #source_weight: 0.5 accou
    #user_token: JedybHhcRHuLqscDENJxgttuyIfkqSnBTYTmtzqI
    
musicbrainz:
    #host: localhost:5000
    #ratelimit: 100
    searchlimit: 7

#beatport:
   
   
   
   
   
   
   
   
   
   
   
   
   