library: library.db
directory: /sdcard/Music/music_in

#IMPORT
import:
    # files
    move: no
    copy: no
    delete: no
    link: no
    hardlink: no

# use mutliple threads
threaded: yes
timeout: 5.0
verbose: yes

# User Interface -------------------
color: yes
ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue
    #terminal_width: 80
    #length_diff_thresh: 10.0

list_format_item: %upper{$artist} - $album - $track $title
list_format_album: %upper{$albumartist} $album
time_format: '%Y-%m-%d %H:%M:%S'
#terminal_encoding: utf8

#plugins --------------------------
plugins: [
    info,
    convert    
]

convert:
    auto: yes
    copy_album_art: no
    embed: yes
    max_bitrate: 320
    format: mp3
    dest: /sdcard/Music/music_in
    formats:
        mp3:
            command: ffmpeg -i $source -ab 320k $dest
            extension: mp3
            # map_metadata 0 -id3v2_version 
#        alac:
#            command: ffmpeg -i $source -y -vn -acodec alac $dest
#            extension: m4a
#        aac:
#            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
#            extension: m4a
#        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
#        flac: ffmpeg -i $source -y -vn -acodec flac $dest
#        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 2 $dest
#        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
#    dest:
#    tmpdir:

pluginpath: []


