environment:
  nodejs_version: "9"
cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> package-lock.json

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -D nyc@11 @oclif/nyc-config@1
test_script:
  - .\bin\run --version
  - .\bin\run --help
  - .\node_modules\.bin\nyc --nycrc-path node_modules/@oclif/nyc-config/.nycrc npm test
after_test:
  - .\node_modules\.bin\nyc --nycrc-path node_modules/@oclif/nyc-config/.nycrc report --reporter text-lcov > coverage.lcov

build: off
