version: 2.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/LeadPipeSoftware/medkit
    steps:
      - checkout
      - run: go get github.com/mitchellh/go-homedir
      - run: go get github.com/spf13/cobra
      - run: go get github.com/spf13/viper
      - run: make build

  deploy:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/LeadPipeSoftware/medkit
    steps:
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
